let productsDB = [
  {
    id: 1,
    idSupplier: 1,
    nombre: "Llanta modelo 1",
    precio: 250,
    description: "Ligeras y aerodinámicas",
    imagen: ["https://freepngimg.com/thumb/wheel_rim/3-2-wheel-rim-free-png-image-thumb.png", "https://freepngimg.com/thumb/racing/88577-flags-angle-racing-necktie-auto-free-download-png-hd-thumb.png"],
    category: "Llanta",
    stock: 3,
    rating: 8.5,
  },
  {
    id: 2,
    idSupplier: 1,
    nombre: "Llanta modelo 2",
    precio: 300,
    description: "Elegantes y seguras",
    imagen: ["https://freepngimg.com/thumb/wheel_rim/6-2-wheel-rim-picture-thumb.png", "https://freepngimg.com/thumb/racing/88577-flags-angle-racing-necktie-auto-free-download-png-hd-thumb.png"],
    category: "Llanta",
    stock: 5,
    rating: 9.5,
  },
  {
    id: 3,
    idSupplier: 2,
    nombre: "Llanta modelo 3",
    precio: 200,
    description: "Estabilidad máxima y mejor diseño",
    imagen: ["https://freepngimg.com/thumb/wheel_rim/1-2-wheel-rim-15.png", "https://freepngimg.com/thumb/racing/88577-flags-angle-racing-necktie-auto-free-download-png-hd-thumb.png"],
    category: "Llanta",
    stock: 10,
    rating: 9.9,
  },
  {
    id: 4,
    idSupplier: 2,
    nombre: "Llanta modelo 4",
    precio: 250,
    description: "Diseño moderno",
    imagen: ["https://freepngimg.com/thumb/wheel_rim/13-2-wheel-rim-png-pic-thumb.png", "https://freepngimg.com/thumb/racing/88577-flags-angle-racing-necktie-auto-free-download-png-hd-thumb.png"],
    category: "Llanta",
    stock: 6,
    rating: 9.4,
  },
  {
    id: 5,
    idSupplier: 3,
    nombre: "Llanta modelo 5",
    precio: 400,
    description: "Imagen futurista",
    imagen: ["https://freepngimg.com/thumb/wheel_rim/15-2-wheel-rim-high-quality-png-thumb.png", "https://freepngimg.com/thumb/racing/88577-flags-angle-racing-necktie-auto-free-download-png-hd-thumb.png"],
    category: "Llanta",
    stock: 9,
    rating: 8.7,
  },
  {
    id: 6,
    idSupplier: 3,
    nombre: "Llanta modelo 6",
    precio: 320,
    description: "Clásicas y elegantes",
    imagen: ["https://freepngimg.com/thumb/wheel_rim/16-2-wheel-rim-transparent-thumb.png", "https://freepngimg.com/thumb/racing/88577-flags-angle-racing-necktie-auto-free-download-png-hd-thumb.png"],
    category: "Llanta",
    stock: 7,
    rating: 9.5,
  },
  {
    id: 7,
    idSupplier: 1,
    nombre: "Llanta modelo 7",
    precio: 470,
    description: "Diseño especial",
    imagen: ["https://freepngimg.com/thumb/wheel_rim/6-2-wheel-rim-picture-thumb.png", "https://freepngimg.com/thumb/racing/88577-flags-angle-racing-necktie-auto-free-download-png-hd-thumb.png"],
    category: "Llanta",
    stock: 8,
    rating: 9.9,
  },
  {
    id: 8,
    idSupplier: 1,
    nombre: "Llanta modelo 8",
    precio: 195,
    description: "Apta paras los mejores circuitos",
    imagen: ["https://freepngimg.com/thumb/wheel_rim/14-2-wheel-rim-png-file-thumb.png", "https://freepngimg.com/thumb/racing/88577-flags-angle-racing-necktie-auto-free-download-png-hd-thumb.png"],
    category: "Llanta",
    stock: 10,
    rating: 9.5,
  },
  {
    id: 9,
    idSupplier: 1,
    nombre: "Llanta modelo 9",
    precio: 345,
    description: "Modernas y seguras",
    imagen: ["https://freepngimg.com/thumb/wheel_rim/8-2-wheel-rim-download-png-thumb.png", "https://freepngimg.com/thumb/racing/88577-flags-angle-racing-necktie-auto-free-download-png-hd-thumb.png"],
    category: "Llanta",
    stock: 7,
    rating: 9.3,
  },
  {
    id: 10,
    idSupplier: 1,
    nombre: "Llanta modelo 10",
    precio: 295,
    description: "Deportivas y sencillas",
    imagen: ["https://freepngimg.com/thumb/wheel_rim/12-2-wheel-rim-png-hd-thumb.png", "https://freepngimg.com/thumb/racing/88577-flags-angle-racing-necktie-auto-free-download-png-hd-thumb.png"],
    category: "Llanta",
    stock: 6,
    rating: 9.6,
  },
];


module.exports = productsDB

