let productsDB = [
  {
    id: 1,
    idSupplier: 1,
    nombre: "Acelgas ecológicas",
    precio: 1.5,
    description: "Hojas grandes y jugosas",
    imagen: ["https://freepngimg.com/thumb/salad/13-salad-leaf-png-image-thumb.png", "https://static.vecteezy.com/system/resources/previews/022/984/730/non_2x/vegetable-transparent-free-png.png"],
    category: "verdura",
    stock: 3,
    rating: 8.5,
  },
  {
    id: 2,
    idSupplier: 1,
    nombre: "Tomate de la huerta",
    precio: 3,
    description: "Delicioso y carnoso",
    imagen: ["https://freepngimg.com/thumb/tomato/6-tomato-png-image.png", "https://static.vecteezy.com/system/resources/previews/022/984/730/non_2x/vegetable-transparent-free-png.png"],
    category: "verdura",
    stock: 5,
    rating: 9.5,
  },
  {
    id: 3,
    idSupplier: 2,
    nombre: "Mandarinas clementinas",
    precio: 2,
    description: "Sabor agradable y suave",
    imagen: ["https://freepngimg.com/thumb/fruit/5-2-fruit-free-png-image-thumb.png", "https://static.vecteezy.com/system/resources/previews/022/984/730/non_2x/vegetable-transparent-free-png.png"],
    category: "fruta",
    stock: 10,
    rating: 9.9,
  },
  {
    id: 4,
    idSupplier: 2,
    nombre: "Plátano de Canarias",
    precio: 3.5,
    description: "El más jugoso y sabroso",
    imagen: ["https://freepngimg.com/thumb/banana/1-banana-png-image-thumb.png", "https://static.vecteezy.com/system/resources/previews/022/984/730/non_2x/vegetable-transparent-free-png.png"],
    category: "fruta",
    stock: 6,
    rating: 9.4,
  },
  {
    id: 5,
    idSupplier: 3,
    nombre: "Brócoli",
    precio: 4.3,
    description: "Textura agradable y sabor excepcional",
    imagen: ["https://freepngimg.com/thumb/broccoli/7-broccoli-png-image-thumb.png", "https://static.vecteezy.com/system/resources/previews/022/984/730/non_2x/vegetable-transparent-free-png.png"],
    category: "verdura",
    stock: 9,
    rating: 8.7,
  },
  {
    id: 6,
    idSupplier: 3,
    nombre: "Verduras variadas lote 1",
    precio: 3.7,
    description: "Deliciosas y frescas",
    imagen: ["https://freepngimg.com/thumb/healthy_food/5-2-healthy-food-png-image-thumb.png", "https://static.vecteezy.com/system/resources/previews/022/984/730/non_2x/vegetable-transparent-free-png.png"],
    category: "verdura",
    stock: 7,
    rating: 9.5,
  },
  {
    id: 7,
    idSupplier: 1,
    nombre: "Verduras variadas lote 2",
    precio: 5.7,
    description: "Ecológicas de la huerta",
    imagen: ["https://freepngimg.com/thumb/healthy_food/4-2-healthy-food-png-file-thumb.png", "https://static.vecteezy.com/system/resources/previews/022/984/730/non_2x/vegetable-transparent-free-png.png"],
    category: "verdura",
    stock: 8,
    rating: 9.9,
  },
  {
    id: 8,
    idSupplier: 1,
    nombre: "Uva negra ecológica",
    precio: 9.8,
    description: "Gran aroma y sabor",
    imagen: ["https://freepngimg.com/thumb/grape/4-grape-png-image-download-picture-thumb.png", "https://static.vecteezy.com/system/resources/previews/022/984/730/non_2x/vegetable-transparent-free-png.png"],
    category: "fruta",
    stock: 10,
    rating: 9.5,
  },
  {
    id: 9,
    idSupplier: 1,
    nombre: "Limón campero",
    precio: 6.7,
    description: "Esquisito olor y sabor",
    imagen: ["https://freepngimg.com/thumb/lemon/4-lemon-png-image-thumb.png", "https://static.vecteezy.com/system/resources/previews/022/984/730/non_2x/vegetable-transparent-free-png.png"],
    category: "fruta",
    stock: 7,
    rating: 9.3,
  },
  {
    id: 10,
    idSupplier: 1,
    nombre: "Fresón de Huelva",
    precio: 5.3,
    description: "Sabor intenso",
    imagen: ["https://freepngimg.com/thumb/strawberry/1-strawberry-png-images-thumb.png", "https://static.vecteezy.com/system/resources/previews/022/984/730/non_2x/vegetable-transparent-free-png.png"],
    category: "fruta",
    stock: 6,
    rating: 9.6,
  },
];


module.exports = productsDB

