let productsDB = [
    {
      id: 1,
      idSupplier: 1,
      nombre: "Tomate huevo de toro",
      precio: 1,
      description: "El más carnoso y sabroso",
      imagen: "https",
      category: "verdura",
      stock: 0,
      rating: 9.5,
    },
    {
      id: 2,
      idSupplier: 1,
      nombre: "Tomate huevo de toro",
      precio: 1,
      description: "El más carnoso y sabroso",
      imagen: "https",
      category: "verdura",
      stock: 0,
      rating: 9.5,
    },
    {
      id: 3,
      idSupplier: 1,
      nombre: "Tomate huevo de toro",
      precio: 1,
      description: "El más carnoso y sabroso",
      imagen: "https",
      category: "verdura",
      stock: 0,
      rating: 9.5,
    },
    {
      id: 4,
      idSupplier: 1,
      nombre: "Tomate huevo de toro",
      precio: 1,
      description: "El más carnoso y sabroso",
      imagen: "https",
      category: "verdura",
      stock: 0,
      rating: 9.5,
    },
    {
      id: 5,
      idSupplier: 1,
      nombre: "Tomate huevo de toro",
      precio: 1,
      description: "El más carnoso y sabroso",
      imagen: "https",
      category: "verdura",
      stock: 0,
      rating: 9.5,
    },
    {
      id: 6,
      idSupplier: 1,
      nombre: "Tomate huevo de toro",
      precio: 1,
      description: "El más carnoso y sabroso",
      imagen: "https",
      category: "verdura",
      stock: 0,
      rating: 9.5,
    },
    {
      id: 7,
      idSupplier: 1,
      nombre: "Tomate huevo de toro",
      precio: 1,
      description: "El más carnoso y sabroso",
      imagen: "https",
      category: "verdura",
      stock: 0,
      rating: 9.5,
    },
    {
      id: 8,
      idSupplier: 1,
      nombre: "Tomate huevo de toro",
      precio: 1,
      description: "El más carnoso y sabroso",
      imagen: "https",
      category: "verdura",
      stock: 0,
      rating: 9.5,
    },
    {
      id: 9,
      idSupplier: 1,
      nombre: "Tomate huevo de toro",
      precio: 1,
      description: "El más carnoso y sabroso",
      imagen: "https",
      category: "verdura",
      stock: 0,
      rating: 9.5,
    },
    {
      id: 10,
      idSupplier: 1,
      nombre: "Tomate huevo de toro",
      precio: 1,
      description: "El más carnoso y sabroso",
      imagen: "https",
      category: "verdura",
      stock: 0,
      rating: 9.5,
    },
    {
      id: 11,
      idSupplier: 1,
      nombre: "Tomate huevo de toro",
      precio: 1,
      description: "El más carnoso y sabroso",
      imagen: "https",
      category: "verdura",
      stock: 0,
      rating: 9.5,
    },
    {
      id: 12,
      idSupplier: 1,
      nombre: "Tomate huevo de toro",
      precio: 1,
      description: "El más carnoso y sabroso",
      imagen: "https",
      category: "verdura",
      stock: 0,
      rating: 9.5,
    },
    {
      id: 13,
      idSupplier: 1,
      nombre: "Tomate huevo de toro",
      precio: 1,
      description: "El más carnoso y sabroso",
      imagen: "https",
      category: "verdura",
      stock: 0,
      rating: 9.5,
    },
    {
      id: 14,
      idSupplier: 1,
      nombre: "Tomate huevo de toro",
      precio: 1,
      description: "El más carnoso y sabroso",
      imagen: "https",
      category: "verdura",
      stock: 0,
      rating: 9.5,
    },
    {
      id: 15,
      idSupplier: 1,
      nombre: "Tomate huevo de toro",
      precio: 1,
      description: "El más carnoso y sabroso",
      imagen: "https",
      category: "verdura",
      stock: 0,
      rating: 9.5,
    },
  ];
  
  
  module.exports = productsDB
  
  